namespace VLGameProject.VLGui {
    public enum ENUMGuiText {
        K_None,
        K_Option_Audio_AudioMixerMaster,
        K_Option_Audio_AudioMixerMusic,
        K_Option_Audio_AudioMixerSfx,
        K_Option_Audio_AudioMixerSfxGui,
        K_Option_Audio_AudioMixerSfxGame,
        K_Option_Audio_AudioMixerVoice,
        K_Currency,
        K_Currency_Money,
        K_Currency_Coin,
        K_Currency_Penny,
        K_Currency_Dime,
        K_Currency_Gem,
        K_Currency_Crystal,
        K_GameplayStat_Health,
        K_GameplayStat_Mana,
        K_GameplayStat_Stamina,
        K_GameplayStat_Energy,
        K_GameplayValue_Health,
        K_GameplayValue_Mana,
        K_GameplayValue_Stamina,
        K_GameplayValue_Energy,
        K_GameplayValue_TimeElapse,
        K_GameplayValue_TimeCountdown,
        K_GameplayValue_TimeLimit,
        K_GameplayValue_Highscore,
        K_GameplayValue_Combo,
        K_GameplayValue_EnemyCount,
        K_GameplayValue_EnemyRemain,
        K_DateTime_Date,
        K_DateTime_Time,
        K_DateTime_DateAndTime,
    }
}

