using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(menuName = "SO/GuiButton")]
public class SOGuiButton : ScriptableObject {

    [Header("EDITOR ONLY")]
    [SerializeField] public ENUM_GUIELEMENT_BUTTON enum_type;

    public void TestGUID() => Debug.Log($"TEST - GUID: ENUM_TYPE: ");

    [Header("DATA")]
    [SerializeField] private string str_guid;
    public void SetTextGUID(string _text) { str_guid = _text; }
    public string GetTextGUID() { return str_guid; }
}

public enum ENUM_GUIELEMENT_BUTTON {
    NONE = 0,

    //COMMON
    K_NEXT = 1,
    K_BACK = 2,
    K_CLOSE = 3,

    //OPEN-PAGE
    K_GOTO_PAGE_PAUSE = 128,
    K_GOTO_PAGE_OPTIONS,
    K_GOTO_PAGE_OPTIONS_AUDIO,
    K_GOTO_PAGE_OPTIONS_DISPLAY,
    K_GOTO_PAGE_OPTIONS_LANGUAGE,
    K_GOTO_PAGE_LEADERBOARD,

    //ASK-PAGE
    K_ASK_RESTART_GAME = 256,
    K_ASK_EXIT_TO_MAINMENU,
    K_ASK_EXIT_TO_OS,
    K_ASK_RESET_SAVE_DATA,

    //FUNCTION-LOADSCENE
    K_LOADSCENE_CURRENT = 384,
    K_LOADSCENE_MAINMENU,
    K_LOADSCENE_GAMEPLAY,
    K_LOADSCENE_GAMEPLAY_RESULT,

    //FUNCTION-OTHERS
    K_FUNCTION_RESUME_GAME = 512,
    K_FUNCTION_PAUSE_GAME,
    K_FUNCTION_RESTART_GAME,
    K_FUNCTION_EXIT_TO_OS,
    K_FUNCTION_RESET_SAVE_DATA,

    //OTHERS
    K_FUNCTION_SET_LANGUAGE = 1024,
    K_FUNCTION_SET_LANGUAGE_ENGLISH,
    K_FUNCTION_SET_LANGUAGE_VIETNAMESE,
}

public class CONST_GUIBUTTON {

    /*    
c1588260-9124-480f-b78d-c6b4634af4d8
987f90a7-f0b9-45cb-bd5d-9e3117ab3529
355c82f5-2e21-43bf-9764-7c6bae5608bf
f673cc0b-72bc-4588-b5bb-27c25172cfe4
c19b9b2f-48f5-4ce6-b8fb-5ca9df107ad9
7b83507a-d102-4035-b23f-d1e16cc1fb43
132c8ced-76fb-466e-92a0-6dd30978dd7e
     */

    public Dictionary<ENUM_GUIELEMENT_BUTTON, string> GetDictType2Str() { return dict_type2str; }
    public Dictionary<string, ENUM_GUIELEMENT_BUTTON> GetDictStr2Type() { return dict_str2type; }
    public ENUM_GUIELEMENT_BUTTON GetTypeButton(string _text) { return dict_str2type[_text]; }
    public string GetGUIDButton(ENUM_GUIELEMENT_BUTTON _type) { return dict_type2str[_type]; }

    private Dictionary<ENUM_GUIELEMENT_BUTTON, string> dict_type2str = new Dictionary<ENUM_GUIELEMENT_BUTTON, string>() {
        {ENUM_GUIELEMENT_BUTTON.K_NEXT, K_NEXT},
        {ENUM_GUIELEMENT_BUTTON.K_BACK, K_BACK},
        {ENUM_GUIELEMENT_BUTTON.K_CLOSE, K_CLOSE},
        {ENUM_GUIELEMENT_BUTTON.K_GOTO_PAGE_PAUSE, K_GOTO_PAGE_PAUSE},
        {ENUM_GUIELEMENT_BUTTON.K_GOTO_PAGE_OPTIONS, K_GOTO_PAGE_OPTIONS},
        {ENUM_GUIELEMENT_BUTTON.K_GOTO_PAGE_OPTIONS_AUDIO, K_GOTO_PAGE_OPTIONS_AUDIO},
        {ENUM_GUIELEMENT_BUTTON.K_GOTO_PAGE_OPTIONS_LANGUAGE, K_GOTO_PAGE_OPTIONS_LANGUAGE},
        {ENUM_GUIELEMENT_BUTTON.K_ASK_RESTART_GAME, K_ASK_RESTART_GAME},
        {ENUM_GUIELEMENT_BUTTON.K_ASK_EXIT_TO_MAINMENU, K_ASK_EXIT_TO_MAINMENU},
        {ENUM_GUIELEMENT_BUTTON.K_ASK_EXIT_TO_OS, K_ASK_EXIT_TO_OS},
        {ENUM_GUIELEMENT_BUTTON.K_ASK_RESET_SAVE_DATA, K_ASK_RESET_SAVE_DATA},
        {ENUM_GUIELEMENT_BUTTON.K_LOADSCENE_CURRENT, K_LOADSCENE_CURRENT},
        {ENUM_GUIELEMENT_BUTTON.K_LOADSCENE_MAINMENU, K_LOADSCENE_MAINMENU},
        {ENUM_GUIELEMENT_BUTTON.K_LOADSCENE_GAMEPLAY, K_LOADSCENE_GAMEPLAY},
        {ENUM_GUIELEMENT_BUTTON.K_LOADSCENE_GAMEPLAY_RESULT, K_LOADSCENE_GAMEPLAY_RESULT},
        {ENUM_GUIELEMENT_BUTTON.K_FUNCTION_RESUME_GAME, K_FUNCTION_RESUME_GAME},
        {ENUM_GUIELEMENT_BUTTON.K_FUNCTION_PAUSE_GAME, K_FUNCTION_PAUSE_GAME},
        {ENUM_GUIELEMENT_BUTTON.K_FUNCTION_RESTART_GAME, K_FUNCTION_RESTART_GAME},
        {ENUM_GUIELEMENT_BUTTON.K_FUNCTION_EXIT_TO_OS, K_FUNCTION_EXIT_TO_OS},
        {ENUM_GUIELEMENT_BUTTON.K_FUNCTION_RESET_SAVE_DATA, K_FUNCTION_RESET_SAVE_DATA},
        {ENUM_GUIELEMENT_BUTTON.K_FUNCTION_SET_LANGUAGE, K_FUNCTION_SET_LANGUAGE},
        {ENUM_GUIELEMENT_BUTTON.K_FUNCTION_SET_LANGUAGE_ENGLISH, K_FUNCTION_SET_LANGUAGE_ENGLISH},
        {ENUM_GUIELEMENT_BUTTON.K_FUNCTION_SET_LANGUAGE_VIETNAMESE, K_FUNCTION_SET_LANGUAGE_VIETNAMESE},
    };

    private Dictionary<string, ENUM_GUIELEMENT_BUTTON> dict_str2type = new Dictionary<string, ENUM_GUIELEMENT_BUTTON>() {
        {K_NEXT, ENUM_GUIELEMENT_BUTTON.K_NEXT},
        {K_BACK, ENUM_GUIELEMENT_BUTTON.K_BACK},
        {K_CLOSE, ENUM_GUIELEMENT_BUTTON.K_CLOSE},
        {K_GOTO_PAGE_PAUSE, ENUM_GUIELEMENT_BUTTON.K_GOTO_PAGE_PAUSE},
        {K_GOTO_PAGE_OPTIONS, ENUM_GUIELEMENT_BUTTON.K_GOTO_PAGE_OPTIONS},
        {K_GOTO_PAGE_OPTIONS_AUDIO, ENUM_GUIELEMENT_BUTTON.K_GOTO_PAGE_OPTIONS_AUDIO},
        {K_GOTO_PAGE_OPTIONS_LANGUAGE, ENUM_GUIELEMENT_BUTTON.K_GOTO_PAGE_OPTIONS_LANGUAGE},
        {K_ASK_RESTART_GAME, ENUM_GUIELEMENT_BUTTON.K_ASK_RESTART_GAME},
        {K_ASK_EXIT_TO_MAINMENU, ENUM_GUIELEMENT_BUTTON.K_ASK_EXIT_TO_MAINMENU},
        {K_ASK_EXIT_TO_OS, ENUM_GUIELEMENT_BUTTON.K_ASK_EXIT_TO_OS},
        {K_ASK_RESET_SAVE_DATA, ENUM_GUIELEMENT_BUTTON.K_ASK_RESET_SAVE_DATA},
        {K_LOADSCENE_CURRENT, ENUM_GUIELEMENT_BUTTON.K_LOADSCENE_CURRENT},
        {K_LOADSCENE_MAINMENU, ENUM_GUIELEMENT_BUTTON.K_LOADSCENE_MAINMENU},
        {K_LOADSCENE_GAMEPLAY, ENUM_GUIELEMENT_BUTTON.K_LOADSCENE_GAMEPLAY},
        {K_LOADSCENE_GAMEPLAY_RESULT, ENUM_GUIELEMENT_BUTTON.K_LOADSCENE_GAMEPLAY_RESULT},
        {K_FUNCTION_RESUME_GAME, ENUM_GUIELEMENT_BUTTON.K_FUNCTION_RESUME_GAME},
        {K_FUNCTION_PAUSE_GAME, ENUM_GUIELEMENT_BUTTON.K_FUNCTION_PAUSE_GAME},
        {K_FUNCTION_RESTART_GAME, ENUM_GUIELEMENT_BUTTON.K_FUNCTION_RESTART_GAME},
        {K_FUNCTION_EXIT_TO_OS, ENUM_GUIELEMENT_BUTTON.K_FUNCTION_EXIT_TO_OS},
        {K_FUNCTION_RESET_SAVE_DATA, ENUM_GUIELEMENT_BUTTON.K_FUNCTION_RESET_SAVE_DATA},
        {K_FUNCTION_SET_LANGUAGE, ENUM_GUIELEMENT_BUTTON.K_FUNCTION_SET_LANGUAGE},
        {K_FUNCTION_SET_LANGUAGE_ENGLISH, ENUM_GUIELEMENT_BUTTON.K_FUNCTION_SET_LANGUAGE_ENGLISH},
        {K_FUNCTION_SET_LANGUAGE_VIETNAMESE, ENUM_GUIELEMENT_BUTTON.K_FUNCTION_SET_LANGUAGE_VIETNAMESE},
    };

    public const string K_NEXT = "621c2720-d1f4-4c3f-96f4-6f054c312c22";
    public const string K_BACK = "aabdb565-2d07-4acf-8953-9e705b481075";
    public const string K_CLOSE = "e7992845-3836-4d7d-b513-a731584dac70";
    public const string K_GOTO_PAGE_PAUSE = "7d1386eb-7a0c-40de-b431-d6bb9d72af58";
    public const string K_GOTO_PAGE_OPTIONS = "b837f9c4-688b-4210-be4d-ed9db8ea5b37";
    public const string K_GOTO_PAGE_OPTIONS_AUDIO = "ebd01e96-df10-454f-b941-64181a6a32c4";
    public const string K_GOTO_PAGE_OPTIONS_LANGUAGE = "dadb2288-f822-48b4-afd1-c76c4360da87";
    public const string K_ASK_RESTART_GAME = "b6abe552-0215-4e88-84b4-e24b09a9a0a6";
    public const string K_ASK_EXIT_TO_MAINMENU = "bf7c2c6b-d399-40e8-9c25-ed0058b82539";
    public const string K_ASK_EXIT_TO_OS = "b944e2aa-f66c-4cc0-957b-1244204ee817";
    public const string K_ASK_RESET_SAVE_DATA = "9bf81ce7-0d2f-4150-9621-efc9faab377d";
    public const string K_LOADSCENE_CURRENT = "fe26ed80-c331-4bf6-a554-0b75da54164e";
    public const string K_LOADSCENE_MAINMENU = "b739c329-6ccd-4aae-bd3b-8451846b4bf5";
    public const string K_LOADSCENE_GAMEPLAY = "0b4e48b9-c842-4490-9a12-029d7c8d1d24";
    public const string K_LOADSCENE_GAMEPLAY_RESULT = "1a2736b9-9da9-468c-8f02-b81696bf2447";
    public const string K_FUNCTION_RESUME_GAME = "a98dcde5-6c5d-4d94-84e7-aa54b0e5f337";
    public const string K_FUNCTION_PAUSE_GAME = "d4185e6d-0be5-4f49-8eeb-4227798f981c";
    public const string K_FUNCTION_RESTART_GAME = "053d7f7e-c4cf-4597-a9c9-4de876bfb394";
    public const string K_FUNCTION_EXIT_TO_OS = "784bcd00-b7b9-4bc5-8f9c-c1799a0ffa0d";
    public const string K_FUNCTION_RESET_SAVE_DATA = "c8f52390-1973-4ac1-a32f-29b57ffaa590";
    public const string K_FUNCTION_SET_LANGUAGE = "eaea8ed8-a678-4448-8a84-c3569e28c489";
    public const string K_FUNCTION_SET_LANGUAGE_ENGLISH = "289aaf54-5dbb-4790-abf4-5ca369df7fde";
    public const string K_FUNCTION_SET_LANGUAGE_VIETNAMESE = "5cbbf46a-e401-461e-887e-2ce2493c5881";
}
